### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by Bijit-Mondal** [alitokmakci/gnb-ui#3]

**Comment by bb7hn** [comment]
I am curuios too. Do you need contribution mate ?

**Comment by Bijit-Mondal** [comment]
For?

**Comment by Bijit-Mondal** [comment]
Please consider developing this project

**Comment by alitokmakci** [comment]
I am planning to build next js components based on this repo. And planning to improve this after that project. I was too busy and could not develop for a long time. Sorry for that. @Bijit-Mondal
